[New] Change status intent
RocketChat/alexa-rocketchat pull request #106
Opened 2020-05-27 20:00 UTC by AdarshNaidu

This simple intent allows the user to set/change status of his profile

### Conversation
**User**: Change status to I will be busy for the whole of coming week.
**Alexa**: Done
OR
**User**: Change status
**Alexa**: Alright, what's the new status?
**User**: I will be busy for the whole of coming week.
**Alexa**: Done.

2020-06-02 20:55 UTC, TheDreamSaver commented
Are we not using intent/slot confirmation here @AdarshNaidu?

2020-06-03 05:58 UTC, AdarshNaidu commented
> Are we not using intent/slot confirmation here @AdarshNaidu?

I thought of keeping the conversation short and concise, since it's just changing status.

2020-06-03 11:46 UTC, TheDreamSaver commented
We should. Because speech to text is never that accurate to get it exactly what you said.
For me, it took something else and set that as a status.

Also, suggest doing all the testing via mic on the console and not the text input until you get a device.

Because the end-user is going to talk and not type.

2020-06-03 15:23 UTC, TheDreamSaver requested changes

2020-06-03 15:23 UTC, TheDreamSaver commented on lambda/custom/resources/en-US.json
>          "SUCCESS": "Done.",
Change it to "Done, I have updated your status."

2020-06-03 15:23 UTC, TheDreamSaver commented on models/en-US.json
> +                                "{statusmessage}"
Try adding 
"change status to {statusmessage}",
"set status to {statusmessage}"

these to the slot elicitation samples as well.

The user once he is asked "Alright, what's the new status?"

He can reply with "set status to {searchquery}"

Currently it is including "set status to" as well.

Check with these two slot utterances if everything works fine,
if yes, add them as well.

2020-07-24 14:16 UTC, closed without merging