[Update] Unread messages intent
RocketChat/alexa-rocketchat pull request #123
Opened 2020-06-28 14:30 UTC by AdarshNaidu

The updated read unread messages intent in this PR can read messages from both public and private channels.

This intent uses simple resolution of channel names. i.e. it will resolve the input to the best matching channel or group name without any intent confirmation.

2020-07-15 07:17 UTC, Wuvist commented
Should updating model with previous intents be in separate PR?

2020-07-23 17:02 UTC, TheDreamSaver requested changes
Sanitize the display text that appears on the screen, currently it shows the break tags from SSML as well.

2020-07-24 10:49 UTC, TheDreamSaver approved these changes

2020-07-24 18:12 UTC, Sing-Li commented
pls resolve conflict thx

2020-08-24 13:30 UTC, TheDreamSaver requested changes

2020-08-24 13:30 UTC, TheDreamSaver commented on models/en-US.json
> +            "invocationName": "test rocket",
Change this.

2020-08-24 15:15 UTC, TheDreamSaver approved these changes

2020-08-25 10:53 UTC, merged