added emoji to PostMessageIntent
RocketChat/alexa-rocketchat pull request #44
Opened 2019-05-05 12:49 UTC by TheDreamSaver

Now you can say, send "I'm feeling happy emoji heart" to general.

2019-05-05 14:02 UTC, PrajvalRaval requested changes
Add a sample utterance to our SampleUtterance file and along with cheatsheet and 3 emoji limit in your PR :thumbsup:

2019-05-05 14:32 UTC, acerbisgianluca requested changes

2019-05-05 14:32 UTC, acerbisgianluca commented on models/en-IN.json
> +                    "name": "GetLastMessageFromChannel",
Please change `GetLastMessageFromChannel` to `GetLastMessageFromChannelIntent` in `models`.

2019-05-05 15:04 UTC, acerbisgianluca approved these changes

2019-05-07 15:19 UTC, PrajvalRaval approved these changes

2019-05-07 20:13 UTC, merged