Quick bug fix
RocketChat/alexa-rocketchat pull request #68
Opened 2020-03-05 13:26 UTC by AdarshNaidu

`await` being used without declaring function as `async`

2020-03-05 16:29 UTC, PrajvalRaval commented
The problem here is that the intent functions here are actually not async, and don't require async property in them. So it will be better if you can instead of adding `async` remove unwanted `awaits` from the functions.

2020-03-05 18:03 UTC, PrajvalRaval approved these changes

2020-03-06 10:25 UTC, TheDreamSaver requested changes
attributesmanager.getPersistentAttributes() uses dynamoDB which is an external service.

Always use it with async/await to make sure the flow proceeds only when the DB data is loaded.

2020-03-06 10:28 UTC, TheDreamSaver commented
Will close #63 as well.

2020-03-06 13:28 UTC, PrajvalRaval approved these changes

2020-03-06 13:34 UTC, TheDreamSaver approved these changes

2020-03-17 00:59 UTC, closed without merging